// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/sum.proto

package sum

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SumRequest struct {
	Number_1             int32    `protobuf:"varint,1,opt,name=number_1,json=number1,proto3" json:"number_1,omitempty"`
	Number_2             int32    `protobuf:"varint,2,opt,name=number_2,json=number2,proto3" json:"number_2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumRequest) Reset()         { *m = SumRequest{} }
func (m *SumRequest) String() string { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()    {}
func (*SumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33af41ac7b8d43b1, []int{0}
}

func (m *SumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRequest.Unmarshal(m, b)
}
func (m *SumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRequest.Marshal(b, m, deterministic)
}
func (m *SumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRequest.Merge(m, src)
}
func (m *SumRequest) XXX_Size() int {
	return xxx_messageInfo_SumRequest.Size(m)
}
func (m *SumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumRequest proto.InternalMessageInfo

func (m *SumRequest) GetNumber_1() int32 {
	if m != nil {
		return m.Number_1
	}
	return 0
}

func (m *SumRequest) GetNumber_2() int32 {
	if m != nil {
		return m.Number_2
	}
	return 0
}

type SumResponse struct {
	SumResult            int32    `protobuf:"varint,1,opt,name=sum_result,json=sumResult,proto3" json:"sum_result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumResponse) Reset()         { *m = SumResponse{} }
func (m *SumResponse) String() string { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()    {}
func (*SumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33af41ac7b8d43b1, []int{1}
}

func (m *SumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumResponse.Unmarshal(m, b)
}
func (m *SumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumResponse.Marshal(b, m, deterministic)
}
func (m *SumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumResponse.Merge(m, src)
}
func (m *SumResponse) XXX_Size() int {
	return xxx_messageInfo_SumResponse.Size(m)
}
func (m *SumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumResponse proto.InternalMessageInfo

func (m *SumResponse) GetSumResult() int32 {
	if m != nil {
		return m.SumResult
	}
	return 0
}

func init() {
	proto.RegisterType((*SumRequest)(nil), "sum.SumRequest")
	proto.RegisterType((*SumResponse)(nil), "sum.SumResponse")
}

func init() { proto.RegisterFile("proto/sum.proto", fileDescriptor_33af41ac7b8d43b1) }

var fileDescriptor_33af41ac7b8d43b1 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x2e, 0xcd, 0xd5, 0x03, 0xb3, 0x84, 0x98, 0x8b, 0x4b, 0x73, 0x95, 0x9c, 0xb8,
	0xb8, 0x82, 0x4b, 0x73, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x24, 0xb9, 0x38, 0xf2,
	0x4a, 0x73, 0x93, 0x52, 0x8b, 0xe2, 0x0d, 0x25, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0xd8, 0x21,
	0x7c, 0x43, 0x24, 0x29, 0x23, 0x09, 0x26, 0x64, 0x29, 0x23, 0x25, 0x1d, 0x2e, 0x6e, 0xb0, 0x19,
	0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0xb2, 0x5c, 0x5c, 0xc5, 0xa5, 0xb9, 0xf1, 0x45, 0xa9,
	0xc5, 0xa5, 0x39, 0x25, 0x50, 0x63, 0x38, 0x8b, 0xc1, 0x0a, 0x4a, 0x73, 0x4a, 0x8c, 0xcc, 0xc0,
	0x36, 0x06, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a, 0x69, 0x70, 0x31, 0x07, 0x97, 0xe6, 0x0a,
	0xf1, 0xeb, 0x81, 0xdc, 0x85, 0x70, 0x89, 0x94, 0x00, 0x42, 0x00, 0x62, 0xac, 0x93, 0x5c, 0x94,
	0x4c, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0xbe, 0x57, 0x62, 0xae, 0x71,
	0x71, 0x46, 0x62, 0x4e, 0x4e, 0x66, 0x4a, 0x62, 0x25, 0xc8, 0x53, 0x49, 0x6c, 0x60, 0x5f, 0x19,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xfc, 0xc5, 0x9d, 0xe8, 0x00, 0x00, 0x00,
}
